services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .backend/.env
    depends_on:
      - mongo
      - redis
      - ml

  ml:
    build: ./ml
    container_name: ml-pipeline
    restart: always

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"